modLoader="javafml"
loaderVersion="[2,)"
license="MIT"

[[mods]]
modId="heracles"
version = "${version}"
displayName="Heracles"
authors="ThatGravyBoat"
description="Heracles is a comprehensive questing mod that allows pack makers to create tree style quests that can be distributed via the config folder for users to play and complete."

[[dependencies.heracles]]
modId="neoforge"
mandatory=true
versionRange="[21,)"
ordering="NONE"
side="BOTH"

[[dependencies.heracles]]
modId="minecraft"
mandatory=true
versionRange="[1.21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.heracles]]
modId = "resourcefullib"
mandatory = true
versionRange = "[2.1.17,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "heracles-common.mixins.json"
